### ISSUE TITLE
Need more messages

### ISSUE THREAD

**Issue by thomas-lebeau** [thomas-lebeau/zut#1]
You are welcome to add more messages, it is so easy it can be your first Pull Request ever :tada: :
- Just fork and clone the repo
- edit the `message.js`file. There is already a category `errors` that can be use to filter message for says success or error warnings.
- commit your changes and submit the PR.

📢📢 Let your creativity slow, gimme some nice catch phrases 🔊🔊

PS: _Message should be in english. but if peoples are interested I will consider add a language options._

**Comment by alexeyzab** [comment]
Hi there!

I've added a few messages just now, hope they are okay.

Thanks.

**Comment by katbow** [comment]
Heya! I added a few new messages. Cheers
